name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: c-hive/gha-npm-cache@v1
        with:
          directory: Pipelines/package-lock.json

      - name: Install JS dependencies
        run: npm install
        
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: Pipelines/package-lock.json
      - run: npm ci
      
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: cidvieira/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}